### ISSUE TITLE
CUDA/GPU Support?

### ISSUE THREAD

**Issue by Ianyliu** [PoliUniLu/cora#21]
When attempting to run functions such as `get_irredundant_systems()` or `get_irredundant_sums()` on datasets with >= 10 conditions, I almost always run into kernel crashes or out of memory errors. There is an option to limit the max_depth for `get_irredundant_sums()`, but no such option for `get_irredundant_systems()` to the best of my knowledge. 

Is there any possibility/plan of using GPU calculations to allow for causal discovery of larger number of conditions?

**Comment by ZuzanaSebb** [comment]
Hi! 

Currently there is no CUDA support for the calculations, but there is a work in progress for heuristic algorithm calculation which will allow to derive a subset of  irredundant systems for larger number of conditions. I will update you once it's available.

**Comment by Ianyliu** [comment]
@ZuzanaSebb Gotcha, thank you!
